const request = require('supertest');
const express = require('express');
const fs = require('fs');
const path = require('path');
const axios = require('axios');
const imagesRouter = require('../src/routes/images');

const app = express();
app.use('/api/images', imagesRouter);

jest.mock('axios');

const CACHE_DIR = path.join(__dirname, '../../cache');

describe('GET /api/images/proxy', () => {
    beforeAll(() => {
        if (!fs.existsSync(CACHE_DIR)) {
            fs.mkdirSync(CACHE_DIR, { recursive: true });
        }
    });

    afterAll(() => {
        // Cleanup cache generated by tests
        if (fs.existsSync(CACHE_DIR)) {
            fs.readdirSync(CACHE_DIR).forEach(file => {
                fs.unlinkSync(path.join(CACHE_DIR, file));
            });
        }
    });

    it('should return 400 if url parameter is missing', async () => {
        const res = await request(app).get('/api/images/proxy');
        expect(res.status).toBe(400);
        expect(res.body.error).toBe('Missing url parameter');
    });

    it('should fetch, optimize, and serve a valid remote image', async () => {
        // Provide a small mock valid PNG payload buffer
        const mockImage = Buffer.from('89504e470d0a1a0a0000000d49484452000000010000000108060000001f15c4890000000a49444154789c63000100000500010d0a2db40000000049454e44ae426082', 'hex');

        axios.get.mockResolvedValueOnce({ data: mockImage });

        const testUrl = 'https://example.com/image.jpg';
        const res = await request(app).get(`/api/images/proxy?url=${encodeURIComponent(testUrl)}`);
        
        expect(res.status).toBe(200);
        expect(res.headers['content-type']).toBe('image/webp');
        expect(res.headers['cache-control']).toBe('public, max-age=31536000');
        expect(axios.get).toHaveBeenCalledWith(testUrl, expect.any(Object));

        // The second request should be served from cache
        const resCached = await request(app).get(`/api/images/proxy?url=${encodeURIComponent(testUrl)}`);
        expect(resCached.status).toBe(200);
        expect(resCached.headers['content-type']).toBe('image/webp');
        
        // Assert axios wasn't called again for the cached request (only called 1 time originally)
        expect(axios.get).toHaveBeenCalledTimes(1);
    });

    it('should return 502 if the external image cannot be fetched', async () => {
        axios.get.mockRejectedValueOnce(new Error('Network error'));
        
        const testUrl = 'https://example.com/broken.png';
        const res = await request(app).get(`/api/images/proxy?url=${encodeURIComponent(testUrl)}`);
        
        expect(res.status).toBe(502);
        expect(res.body.error).toBe('Failed to fetch or process external image');
    });

    it('should return 502 if sharp fails to process an invalid body', async () => {
        axios.get.mockResolvedValueOnce({ data: Buffer.from("not_an_image") });
        
        const testUrl = 'https://example.com/invalid.jpg';
        const res = await request(app).get(`/api/images/proxy?url=${encodeURIComponent(testUrl)}`);
        
        expect(res.status).toBe(502);
        expect(res.body.error).toBe('Failed to fetch or process external image');
    });
});
